### ISSUE TITLE
support tags without `v`

### ISSUE THREAD

**Issue by aviramha** [bewuethr/release-tracker-action#43]
Thanks for the action. I thought it wasn't working for me then realized it only works with `vmajor.minor.patch` and not with `major.minor.patch`.
I was thinking maybe we can add support for that - not sure how to do the flagging though.
for now I will change in our fork to just use the regex without the `v`

**Comment by bewuethr** [comment]
I could add it as an option that defaults to the current behaviour, but if enabled, skips the `v`? Used something like

```yaml
      - name: Update major version and latest tags
        uses: bewuethr/release-tracker-action@v1
        env:
          # GitHub token to enable pushing tags
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Move "latest" tag
          update-latest: true
          # Don't update the vX.Y tags
          update-minor: false
          # Use X.Y.Z instead of vX.Y.Z, default true
          prepend-v: false
```
